### ISSUE TITLE
Fullstack-projektin koodikatselmointi

### ISSUE THREAD

**Issue by ShootingStar91** [Samuliej/mobileChatApp#63]
# Fullstack-projektin koodikatselmointi

Tämä on katselmointi fullstack-projektistasi. Voit halutessasi hyödyntää tässä annettuja vinkkejä ja parannusehdotuksia, mutta sinun ei tarvitse tehdä muutoksia projektiisi saadaksesi siitä suorituksen.

### Palaute käyttäjäkokemuksesta

+ Sovellus on näppärä käyttää
+ Ulkoasu on myös varsin tyylikäs
+ Navigoiminen ja asioiden löytäminen on helppoa
+ Rekisteröityminen ja kirjautuminen toimi hyvin
+ Sovellus tarjoaa hyvät ominaisuudet sosiaaliseen kanssakäymiseen: Chat, postaukset, feedi, ystävien lisääminen
+ Ehkä vielä olisi hyvä olla jokin tapa löytää käyttäjiä, mikä ei vaatisi käyttäjän nimen tietämistä ennalta, jotta voi löytää myös uusia tuttavuuksia tai sellaisia joiden käyttäjänimeä ei tiedä
+ Käyttäjäkokemus oli kaikin puolin virheetön ja toimiva. Hienoa työtä!

### Palaute koodista 

+ Palvelimen koodi on selkeää ja hyvin jaoteltua
+ Selkeyttä voisi parantaa vielä käyttämällä express-async-errors-kirjastoa, joka nappaa automaattisesti virheet jotka tapahtuu routeissa. Tällöin ei tarvitse laittaa routeja try-catch-koodiin vaan virheenhallinnan voi hoitaa virheenhallinta-middlewaressa.
+ Middlewareja on käytetty fiksusti
+ Frontendin React Native -koodi näyttää myös hyvältä. Luettavaa ja hyvin jaoteltua
+ Contexteja ja hookkeja käytetty hyvin
+ Kommentointi on paikoin ehkä omaan makuun hieman liian runsasta: harva koodia lukeva tarvitsee selityksen siitä, mihin useEffectiä tai useStatea jossain komponentissa käytetään, vaan sen näkee kyllä itse koodista. Tällainen tieto lähinnä lisää tekstiä mikä vaikeuttaa olennaisemman tiedon löytämistä tekstin seasta.

### Yhteenveto

Sovellus on varsin toimiva sosiaalisen median mobiilisovellus. Se on helppokäyttöinen eikä siitä löytynyt yhtään bugia. Sovelluksessa voi lisätä ystäviä, kirjoittaa postauksia ja kommentteja niihin, chättäillä ja muokata profiilia. Käyttökokemus oli mainio. Koodi on myös selkeää ja luettavaa ja hyvin organisoitua. Hyvää työtä! :tada:

**Comment by Samuliej** [comment]
Kiitoksia kattavasta palautteesta!

Minulla oli tarkoituksena kehittää vielä uusien käyttäjien etsintään liittyviä toiminnallisuuksia, mutta halusin saada tuntimäärässä aikaiseksi käytettävän sovelluksen. Tulen toki vielä jatkamaan projektin kehitystä omalla ajallani ja varsinkin juuri virheiden havaitsemista ja käsittelyä haluan parantaa sovelluksessani.
